---
- name: Ensure '{{ deployment_workdir }}' exists
  ansible.builtin.file:
    path: "{{ deployment_workdir }}"
    state: directory
    mode: '0755'

- name: Install and upgrade pip
  ansible.builtin.pip:
    name: pip
    extra_args: --upgrade
    executable: pip3

- name: Ensure python3-pip is installed
  become: true
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: Install python3 modules
  become: true
  ansible.builtin.pip:
    name: "{{ item }}"
    state: forcereinstall
  loop:
    - bottle
    - docker-compose

- name: Install dxlmispservice with pip3
  become: true
  ansible.builtin.pip:
    name: dxlmispservice

- name: Ensure pkg-config is installed
  become: true
  ansible.builtin.apt:
    name: pkg-config
    state: present

- name: Install setuptools-rust with pip3
  become: true
  ansible.builtin.pip:
    name: setuptools-rust

- name: Install docker-compose with pip
  become: true
  ansible.builtin.pip:
    name: docker-compose

- name: Show ansible_python
  ansible.builtin.debug:
    msg: "{{ ansible_python }}"

- name: Copying the Keycloak Directory and its contents
  become: true
  ansible.builtin.copy:
    src: "{{ deployment_resources }}"
    dest: "{{ deployment_workdir }}/"
    owner: "{{ deployment_user }}"
    group: "{{ deployment_group }}"
    mode: '0755'

- name: Transfer a JAR artifact to the remote server
  ansible.builtin.copy:
    src: "{{ deployment_api_jar_src }}"
    dest: "{{ deployment_api_jar_workdir }}/api-backend-0.0.1-SNAPSHOT.jar"
    owner: "{{ deployment_user }}"
    group: "{{ deployment_group }}"
    mode: '0755'

- name: Transfer a Docker artifact to the remote server
  ansible.builtin.copy:
    src: "{{ deployment_artifact }}"
    dest: "{{ deployment_workdir }}/docker-compose.yml"
    owner: "{{ deployment_user }}"
    group: "{{ deployment_group }}"
    mode: '0755'

- name: Setup environment variables
  ansible.builtin.template:
    src: env.j2
    dest: "{{ deployment_workdir }}/.env"
    owner: "{{ deployment_user }}"
    group: "{{ deployment_group }}"
    mode: '0640'

- name: Stop docker-compose
  community.docker.docker_compose:
    project_src: "{{ deployment_workdir }}"
    state: absent
    files:
      - docker-compose.yml

- name: Start docker-compose
  community.docker.docker_compose:
    project_src: "{{ deployment_workdir }}"
    state: present
    files:
      - docker-compose.yml

