---
- name: Ensure '{{ deployment_workdir }}' exists
  ansible.builtin.file:
    path: "{{ deployment_workdir }}"
    state: directory
    mode: 0755

- name: Copying the Keycloak Directory and its contents
  become: true 
  copy:
    src: "{{ deployment_resources }}"
    dest: "{{ deployment_workdir }}/"
    owner: "{{ deployment_user }}"
    group: "{{ deployment_group }}"
    mode: 0755

- name: Transfer an artifact to the remote server
  ansible.builtin.copy:
    src: "{{ deployment_artifact }}"
    dest: "{{ deployment_workdir }}/docker-compose.yml"
    owner: "{{ deployment_user }}"
    group: "{{ deployment_group }}"
    mode: 0755
  notify: restart_app

- name: Setup environment variables
  ansible.builtin.template:
    src: env.j2
    dest: "{{ deployment_workdir }}/.env"
    owner: "{{ deployment_user }}"
    group: "{{ deployment_group }}"
    mode: 0640
  notify: restart_app

- name: Stop docker-compose
  shell:
    cmd: "docker-compose -f docker-compose.yml down -v"
    chdir: "{{ deployment_workdir }}"

- name: Start docker-compose
  shell:
    cmd: "docker-compose -f docker-compose.yml up -d"
    chdir: "{{ deployment_workdir }}"

